
        <div class="moh-left-nav" >
            <a href="<?php echo $this->url('information') ?>"> Information</a><br>
            <a href=""> Work plan</a> <br>
            <a href="<?php echo $this->url('weeklyreport') ?>"> Weekly Report</a><br>  
            
        </div>
    
        <div  class="moh-content">
                 
 
            <?php 
          
                foreach ($this->Studentinfo as $student) :
                    echo 'Student Name     : '.$student['Student_Name'].'<br/><br/>';
                    echo 'Student ID       : '.$student['Student_id'].'<br/><br/>';
                    echo 'Company Name     : '.$student['org_name'].'.<br/><br/>';
                    echo 'Supervisor       : '.$student['super_name'].'<br/><br/>';
                    echo 'Supervisor phone : '.$student['phone'].'<br/><br/>';
                    echo 'Mentor Name      : '.$student['Teacher_FirstName']. ' '.$student['Teacher_LastName'].'<br/><br/>';
                endforeach; 
            ?>
            
              </div>
    
   <!-- <div class="clear"> </div> -->
 