
        <div class="moh-left-nav" >
            <a href="<?php echo $this->url('workplacement') ?>"> Information</a><br>
            <a href="<?php echo $this->url('workplan') ?>"> Work plan</a> <br>
            <a href="<?php echo $this->url('weeklyreport') ?>"> Weekly Report</a><br>
            <a href="<?php echo $this->url('upload') ?>"> Student files </a><br>
        </div>
    
        <div  class="moh-content">
            <h2>Students Files </h2> 
            <a href="./files/stbook.docx" > Student logbook </a><br><br>
            <a href="./files/project.docx" > Project guidelines </a><br><br>
            <hr>
 
            <?php 
                if ($this->count != 0){
                    foreach ($this->Studentinfo as $student) :
                        echo 'Please send your presentation to the following email address : <a href="mailto:'.$student['t_e_mail'].'">'.$student['t_e_mail'].'</a><br/><br/>';
                    endforeach; 
                }
            ?>
            
        </div>
    
   <!-- <div class="clear"> </div> -->
 
