
       <div class="moh-left-nav" >
            <a href="<?php echo $this->url('workplacement') ?>"> Information</a><br>
            <a href="<?php echo $this->url('workplan') ?>"> Work plan</a> <br>
            <a href="<?php echo $this->url('weeklyreport') ?>"> Weekly Report</a><br>
            <a href="<?php echo $this->url('upload') ?>"> Student files </a><br>
        </div>
    
        <div  class="moh-content">
            <h2>Students Files </h2>  
            <hr>
           <?php 
           if ($this->step =="1")
           {
               echo '<h3>File inserted successfully</h3>';
           }
           else {
           ?>
         <form method="post" style="width: 100%; margin: auto;">
		<table width="50%" border="0" cellpadding="1" cellspacing="1" >
                    <tr> 
			<td width="50%">
                            <input type="hidden" name="MAX_FILE_SIZE" value="2000000">
                            <input name="file_name" type="file" id="userfile"> 
			</td>
                        <td width="15%"><input name="upload" type="submit"  id="upload" value=" Upload "></td>
                    </tr>
						
		</table>
            </form>
	<?php  } ?>
            
        </div>