
        <div class="moh-left-nav" >
            <a href="<?php echo $this->url('workplacement') ?>"> Information</a><br>
            <a href="<?php echo $this->url('workplan') ?>"> Work plan</a> <br>
            <a href="<?php echo $this->url('weeklyreport') ?>"> Weekly Report</a><br>
            <a href="<?php echo $this->url('upload') ?>"> Student files </a><br>
        </div>
    
        <div  class="moh-content">
                 
 
            <?php 
                if ($this->count == 0){
                    foreach ($this->Studentinfo as $student) :
                        echo 'Student Name     : '.$student['Student_Name'].'<br/><br/>';
                        echo 'Student ID       : '.$student['Student_id'].'<br/><br/>';
                        echo 'No mentor assigned <br/><br/>';
                        echo 'No supervisor assigned <br/><br/>';
                    endforeach; 
                }else{
                    foreach ($this->Studentinfo as $student) :
                        echo 'Student Name     : '.$student['Student_Name'].'<br/><br/>';
                        echo 'Student ID       : '.$student['Student_id'].'<br/><br/>';
                        echo 'Company Name     : '.$student['Company_Name'].'.<br/><br/>';
                        echo 'Company branch   : '.$student['branch'].'.<br/><br/>';
                        echo 'Supervisor       : '.$student['super_name'].'<br/><br/>';
                        echo 'Supervisor phone : '.$student['phone'].'<br/><br/>';
                        echo 'Supervisor Email : '.$student['e_mail'].'<br/><br/>';
                        echo 'Mentor Name      : '.$student['Teacher_FirstName']. ' '.$student['Teacher_LastName'].'<br/><br/>';
                        echo 'Mentor phone      : '.$student['t_phone'].'<br/><br/>';
                        echo 'Mentor Email      : '.$student['t_e_mail'].'<br/><br/>';
                    endforeach; 
                }
            ?>
            
        </div>
    
   <!-- <div class="clear"> </div> -->
 
