<script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('clock').innerHTML =
    h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>

<?php
$count=0; 
echo $this->username;
echo date("l jS \of F Y ");
 echo '<span id="clock"></span>';
 if ($this->Step != "3"){
 echo '<br/>Period '.$this->period;
 }
if ($this->Step == "1"){
 
?>
 <form action ="" method="post" style="width: 25%; margin: auto;">
    <input list="sections" name="section">
        <datalist id="sections">
            <?php 
                foreach ($this->sections as $section) :
            ?>
                    <option  value="<?php echo $this->escapeHtml($section->Section_id) ?>">
            <?php
                endforeach; 
            ?>
        </datalist>
    </input>
    <input type="submit" value="Next" name="next-but">
 </form>   
<?php 
}else if ($this->Step == "2"){ 

?>
    <div id ="att_header">
     <form action ="" method="post" style="width: 25%; margin: auto;">

        </div> <!-- att_header -->    
            <table border="1" style="width:100%">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th> P </th>
                    <th> L </th>
                    <th> AL </th>
                    <th> A </th>
                </tr>
<?php
foreach ($this->students as $student){
  $count= $count + 1;
?>
    <tr>
        <th><input type ="text" name ="<?php echo 'student'.$count ?>" value=" <?php echo $student['Student_id'] ?>" </th>
        <th><?php echo $student['Student_FirstName']  . '  ' .$student['Student_MiddleName'] . '  ' .$student['Student_LastName']; ?>  </th>
        <th> <input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="0" checked="checked"> </th>
        <th> <input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="1" > </th>
        <th> <input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="2" > </th>
        <th> <input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="3" > </th>
    </tr>   
 <?php
 }
 ?>
      </table>
            <input type="hidden" value="<?php echo $count?>" name="stcount">
           
            <input type="submit" value="submit" name="submit-but">
        </form>
    </div>
<?php }else if ($this->Step == "3"){
    
   // $temp = $this->att ; 
    echo ' <hr>';
    echo ' <br> <b> Attendance table updated successfully </b> ' ;
 }?>