<script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('clock').innerHTML =
    h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>

<div class="teacher-top">
    <div class="teacher-tleft">
        <h1 class="box-title">PROFILE</h1>
        <div class="boxcontent">
            ccccc
        </div>
    </div>
    <div class="teacher-tright">
        <h1 class="box-title">DAILY SCHEDULE</h1>
        <div class="boxcontent">
            ccccc
        </div>
    </div>
</div>
<div class="teacher-bottom">
    <div class="teacher-bleft">
        <h1 class="box-title">CHECK-IN</h1>
        <div class="boxcontent">
            <div class="check-in-title">
                    <?php
                        echo date("l jS \of F Y");
                    ?>
                    <span id="clock"></span>
                <h2>
                    You are not checked-in for today's shift
                </h2>
                <div style="width: 50%; margin: auto;">
                    <input value="Check-in" name="admin_log_but" type="submit" class="btn btn-primary btn-block btn-large" />
                </div>
            </div>
        </div>
    </div>
    <div class="teacher-bright">
        <h1 class="box-title">SECTIONS</h1>
        <div class="boxcontent">
            ccccc
        </div>
    </div>
</div>