<form method="post" onsubmit="return PassValid()" autocomplete="off">
    <?php 
     foreach ($this->Teachertinfo as $tinfo){ 
    ?>
    <div class="stlistpro">
        <div class="stlistprotop">
            <div class="stlistprotopname">
                <?php  echo $tinfo['Teacher_FirstName'].' '.$tinfo['Teacher_LastName'] ?>
            </div>
            <div class="stlistprotophid">
                <?php 
                    if ($tinfo['Teacher_id'] == ""){
                        echo "No ID";
                    }else{
                        echo $tinfo['Teacher_id'];
                    }
                ?>
            </div>
        </div>
        <div class="stlistprobottom" style="width: 100%; height: 450px;">
            <div class="stlistprobottomleft" style="width: 100%;">
                <h3 style="text-align: center; text-transform: uppercase;">Enter your details</h3>
                <input type="hidden" value="<?php echo $tinfo['Teacher_id'] ?>" name="tidprofile">
                <label style="width: 30%;">Email</label><input style="width: 100%;" type="text" id="t-email" name="t-email" value="<?php echo $tinfo['t_e_mail'] ?>" placeholder="Enter your email" />
                <br/><br/><label style="width: 30%;">Mobile</label><input style="width: 100%;" type="text" id="t-mobile" name="t-mobile" value="<?php echo $tinfo['t_phone'] ?>" placeholder="Enter your mobile number" />
                <input autocomplete="off" type="text" value=" " style="display: none;" placeholder="Enter your email" />
                <br/><br/><label style="width: 30%;">New Password</label><input style="width: 100%;" type="password" placeholder="Password" name="tpass" id="tpass" />
                <br/><br/><label style="width: 30%;">Confirm Password</label><input style="width: 100%;" type="password" placeholder="Confirm Password" name="confirm-tpass" id="confirm-tpass" />
            </div>
        </div>
    </div> 
    <?php
        }
    ?>
    <input style="width: 40%; margin-left: 30%;" type="submit" value="Save" name="save-tprofile">
</form>

<script>
    function PassValid() {
        var pass1 = document.getElementById("tpass").value;
        var pass2 = document.getElementById("confirm-tpass").value;
        
        var stemail = document.getElementById("t-email").value;
        var stmobile = document.getElementById("t-mobile").value;
        var ok = true;
        
        if (temail === ""){
            alert("Please write your Email");
            ok = false;
        }else if (tmobile === ""){
            alert("Please write your Mobile");
            ok = false;
        }else if (pass1 !== pass2) {
            alert("Please match Password and Confirmation");
            ok = false;
        }
        
        return ok;
    }
</script>