<div class="sttabs">
    <ul class="sttab-links">
        <?php 
            $i=0;
            foreach ($this->sections as $section) :
                if($i==0){
                    $i++;
        ?>
                    <li class="active"><a href="#<?php echo $i ?>"><?php echo 'Section '.$section['section'] ?></a></li>
        <?php
                }else{
                    $i++;
        ?>          
                    <li><a href="#<?php echo $i ?>"><?php echo 'Section '.$section['section'] ?></a></li>
        <?php
                }
            endforeach; 
        ?>
    </ul>
 
    <div class="sttab-content">
        <?php 
            $j=0;
            foreach ($this->sections2 as $section2) :
                if($j==0){
                    $j++;
        ?>
                    <div id="<?php echo $j ?>" class="sttab active">
                        <table border="1" style="width:100%">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th> Section </th>
                            </tr>
                        <?php 
                        foreach ($this->students as $student){
                            if ($section2['section'] == $student['Student_Section']){
                        ?>
                            
                            <tr>
                                <th><?php echo $student['Student_id'] ?></th>
                                <th><?php echo $student['Student_FirstName'].' '.$student['Student_MiddleName'].' '.$student['Student_LastName'] ?></th>
                                <th><?php echo $student['Student_Section'] ?></th>
                            </tr>
                            
                        <?php 
                            }}
                        ?>
                        </table>
                    </div>
                    
        <?php
                }else{
                    $j++;
        ?>
                    <div id="<?php echo $j ?>" class="sttab">
                        <table border="1" style="width:100%">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th> Section </th>
                            </tr>
                        <?php 
                        foreach ($this->students as $student){
                            if ($section2['section'] == $student['Student_Section']){
                        ?>
                            
                            <tr>
                                <th><?php echo $student['Student_id'] ?></th>
                                <th><?php echo $student['Student_FirstName'].' '.$student['Student_MiddleName'].' '.$student['Student_LastName'] ?></th>
                                <th><?php echo $student['Student_Section'] ?></th>
                            </tr>
                            
                        <?php 
                            }}
                        ?>
                        </table>
                    </div>
        <?php
                }
            endforeach; 
        ?>
    </div>
</div>