
   <div class="moh-left-nav" >
           
            <a href="<?php echo $this->url('toverview') ?>"> Over View</a><br>
            <hr width="90%">
            <form method="post" style="width: 90%; margin: auto;">

             <!-- Students names-->
             <select id="students" name="student" style="width:100%;">
                <?php 
                    foreach ($this->info as $student) :
                ?>
                <option  value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?> - </option>
                <?php
                    endforeach; 
                ?>
            </select>
            <br>
            </form>
            
            <a href="<?php echo $this->url('stwp') ?>"> Work plan</a> <br>
            <a href="#"> Weekly Report</a><br>
            <a href="#"> Evaluation Reports</a><br>
            <a href="#"> Final Evaluation Report</a><br>
            <a href="#"> Project file </a><br>
           
        </div>
    
        <div  class="moh-content">
                 
            <center><h3> Student Work plan </h3></center>
            
                
                 

              
       
            
            
        </div>
 