<?php
    $i =0;
    $studentlistid = 0;
?>
<div class="moh-left-nav" >
        <a href="<?php echo $this->url('toverview') ?>"> Overview</a><br>
        <hr width="90%">
        <form method="post" style="width: 90%; margin: auto;">
            <!-- Students names-->
            <select id="studentslist" name="studentlist" onchange="changeStudent();" style="width:100%;">
               <?php 
                   foreach ($this->info as $student) :
                       if ($i == 0){
                           $studentlistid = $student['sid'];
                       }
                       $i++;
               ?>
               <option  value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
               <?php
                   endforeach; 
               ?>
           </select>
           <br>
        </form>

        <a href="<?php echo $this->url('stwp', array(), array('query' => array('sid' => $studentlistid)));?>"> Work plan </a> <br>
        <a href="<?php echo $this->url('stwr', array(), array('query' => array('sid' => $studentlistid)));?>"> Weekly Reports</a><br>
        <a href="#"> Evaluation Reports</a><br>
        <a href="#"> Final Evaluation Report</a><br>
        <a href="#"> Project file </a><br>

    </div>

    <div  class="moh-content">
        <center><h3> Overview </h3></center>
        <table border="1" style="width:100%" cellpadding="7">
            <tr>
                <th> Student ID          </th>
                <th> Student Name        </th>
                <th> Student Mobile      </th>
           <th> Student Email       </th>
                <th> Employer            </th>
                <th> Supervisor Name     </th>
                <th> Supervisor Mobile   </th>
                <th> Supervisor Email    </th> 

            </tr>

            <?php
                $conut=0;
                foreach ($this->info as $student){

            ?>
            <tr>

                 <td> <?php echo $student['Student_id'] ?></td>
                 <td> <?php echo $student['Student_Name'] ?></td>
                 <td> <?php echo $student['smobile'] ?></td>
                 <td> <?php echo $student['semail'] ?></td>
                 <td> <?php echo $student['Company_Name'] ?></td>
                 <td> <?php echo $student['super_name'] ?></td>
                 <td> <?php echo $student['phone'] ?></td>
                 <td> <?php echo $student['e_mail'] ?></td>
            </tr>   
        <?php
            } //foreach
        ?>
        </table>
</div>
 
<script>
    function changeStudent() {
       var stlist = document.getElementById('studentslist');
       window.location.replace("./stwp?sid="+stlist.value);
    }
</script>