<?php
    $i =0;
    $studentlistid = 0;
?>
<div class="moh-left-nav" >
        <a href="<?php echo $this->url('toverview') ?>"> Overview</a><br>
        <hr width="90%">
        <form method="post" style="width: 90%; margin: auto;">
            <!-- Students names-->
            <select id="studentslist" name="studentlist" onchange="changeStudent();" style="width:100%;">
               <?php 
                   foreach ($this->info as $student) :
                       if ($i == 0){
                           $studentlistid = $student['sid'];
                       }
                       $i++;
               ?>
               <option  value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
               <?php
                   endforeach; 
               ?>
           </select>
           <br>
        </form>

        <a href="<?php echo $this->url('stwp', array(), array('query' => array('sid' => $studentlistid)));?>"> Work plan </a> <br>
        <a href="<?php echo $this->url('stwr', array(), array('query' => array('sid' => $studentlistid)));?>"> Weekly Reports</a><br>
        <a href="<?php echo $this->url('ster', array(), array('query' => array('sid' => $studentlistid)));?>"> Evaluation Reports</a><br>
        <a href="<?php echo $this->url('stfe', array(), array('query' => array('sid' => $studentlistid)));?>"> Final Evaluation Report</a><br>
    </div>

    <div  class="moh-content">
         <h2>Students Files </h2> 
            <a href="./files/stbook.docx" > Student logbook </a><br><br>
            <a href="./files/project.docx" > Project guidelines </a><br><br>
            <hr>
        
        
        <center><h3> Overview </h3></center>
    <?php
        $stud = "";
        foreach ($this->info as $student) :
            if($stud != $student['Company_Name']){
                if($stud != ""){
                ?>
                    </table>
                    </article>
                <?php
                }
                $stud = $student['Company_Name'];
            ?>
            <article class="companylist">
                <p style="margin: 0px; font-weight: bold;"><?php echo $student['Company_Name'] ?></p>
                <p style="margin: 0px;"><?php echo $student['super_name'] ?></p>
                <p style="margin: 0px;"><?php echo $student['phone'] ?></p>
                <p style="margin: 0px;"><?php echo $student['e_mail'] ?></p><hr>
                <table style="width: 95%; margin: auto;"  border="1" cellpadding="7">
                    <tr>
                        <th style="text-align: left;">Name</th>
                        <th style="text-align: left;">Phone</th>
                        <th style="text-align: left;">Email</th>
                    </tr>
            <?php
            }
            ?>
                <tr>
                    <td width="30%" ><?php echo $student['Student_Name']?></td>
                    <td width="35%"><?php  echo $student['smobile']?></td>
                    <td width="35%" ><?php echo $student['semail']?></td>
               </tr>  
            <?php              
        endforeach;
    ?>
        </table>
    </article>
</div>
 
<script>
    function changeStudent() {
       var stlist = document.getElementById('studentslist');
       window.location.replace("./stwp?sid="+stlist.value);
    }
</script>