
   <div class="moh-left-nav" >
           
            <a href="<?php echo $this->url('toverview') ?>"> Over View</a><br>
            <hr width="90%">
            <form method="post" style="width: 90%; margin: auto;">

             <!-- Students names-->
             <select id="students" name="student" style="width:100%;">
                <?php 
                    foreach ($this->info as $student) :
                ?>
                <option  value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?> - </option>
                <?php
                    endforeach; 
                ?>
            </select>
            <br>
            </form>
            
            <a href="<?php echo $this->url('stwp') ?>"> Work plan</a> <br>
            <a href="#"> Weekly Report</a><br>
            <a href="#"> Evaluation Reports</a><br>
            <a href="#"> Final Evaluation Report</a><br>
            <a href="#"> Project file </a><br>
           
        </div>
    
        <div  class="moh-content">
                 
            <center><h3> Over view </h3></center>
            
                
                  <table border="1" style="width:100%" cellpadding="7">
                               <tr>
                                   <th>Sr</th>
                                   <th> Student ID          </th>
                                   <th> Student Name        </th>
                                   <th> Student Mobile      </th>
                              <!--     <th> Student Email       </th>  -->
                                   <th> Employer            </th>
                                   <th> Supervisor Name     </th>
                                   <th> Supervisor Mobile   </th>
                                   <th> Supervisor Email    </th> 

                               </tr>

                           <?php
                               $conut=0;
                               foreach ($this->info as $student){

                               ?>
                               <tr>

                                    <td width="5%" > <?php echo  ++$conut ?></td>
                                    <td width="25%"> <?php echo $student['Student_id'] ?></td>
                                    <td width="50%"> <?php echo $student['Student_Name'] ?></td>
                                    <td width="50%"> <?php echo $student['smobile'] ?></td>
                                   
                                    <td width="50%"> <?php echo $student['Company_Name'] ?></td>
                                    <td width="50%"> <?php echo $student['super_name'] ?></td>
                                    <td width="50%"> <?php echo $student['phone'] ?></td>
                                    <td width="50%"> <?php echo $student['e_mail'] ?></td>
                                    
                                      
                               </tr>   
                       <?php
                       } //foreach
                           ?>
                       </table>

              
       
            
            
        </div>
 