<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Injaz Fujairah</title>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
        <!-- Load jQuery UI CSS  -->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

        <!-- Load jQuery JS -->
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <!-- Load jQuery UI Main JS  -->
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <script>
            jQuery(document).ready(function() {
                jQuery('.sttabs .sttab-links a').on('click', function(e)  {
                    var currentAttrValue = jQuery(this).attr('href');

                    // Show/Hide Tabs
                    jQuery('.sttabs ' + currentAttrValue).show().siblings().hide();

                    // Change/remove current tab to active
                    jQuery(this).parent('li').addClass('active').siblings().removeClass('active');

                    e.preventDefault();
                });
            });
            
            $(document).ready(
                /* This is the function that will get executed after the DOM is fully loaded */
                function () {
                  $( "#sdatepicker" ).datepicker({
                    changeMonth: true,//this option for allowing user to select month
                    changeYear: true //this option for allowing user to select from year range
                  });
                  $( "#edatepicker" ).datepicker({
                    changeMonth: true,//this option for allowing user to select month
                    changeYear: true //this option for allowing user to select from year range
                  });
                }

            );
        </script>
    </head>
    <body onload="startTime()">
        <nav class="nbar">
            <ul class="nbar-list">
                <li class="nbar-link">
                    <a href="<?php echo $this->url('adminHome') ?>">Attendance</a>
                </li>
                <li class="nbar-link">
                    <a href="<?php echo $this->url('adminstudents') ?>">Students</a>
                </li>
                <li class="nbar-link">
                    <a href="">Grades</a>
                </li>
                <li class="nbar-link">
                    <a href="<?php echo $this->url('teacherLogout') ?>">Logout</a>
                </li>
            </ul>
        </nav>
        <div class="teachercontainer">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer>
            <center><p>&copy; 2015 Injaz Fujairah</p></center>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>