<?php
    $stname="";
?>
<div class="moh-left-nav" >
    <a href="<?php echo $this->url('supworkplacement') ?>">Overview</a><br>
    <hr width="90%">
    <form method="post" style="width: 90%; margin: auto;">
        <!-- Students names-->
        <select id="studentslist" name="studentlist" onchange="changeStudent();" style="width:100%;">
           <?php 
                 foreach ($this->info as $student) :
                     if ($this->sid == $student['sid']){
                         $stname = $student['Student_Name'];
             ?>

             <option selected="selected" value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
             <?php
                     }else{
             ?>
             <option value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
             <?php
                     }
                 endforeach; 

             ?>
       </select>
       <br>
    </form>

    <a href="<?php echo $this->url('supworkplan', array(), array('query' => array('sid' => $this->sid)));?>"> Work plan </a> <br>
    <a href="<?php echo $this->url('supweeklyreport', array(), array('query' => array('sid' => $this->sid)));?>"> Evaluation Reports</a><br>
    <a href="<?php echo $this->url('supfinalreport', array(), array('query' => array('sid' => $this->sid)));?>"> Final Evaluation Report</a><br>
</div>

<div  class="moh-content">
    <center><h3><?php echo $stname; ?></h3></center>
    <center><h3>Final evaluation</h3></center>
    <form method="post" style="width: 100%; margin: auto;">
        <table border="1" style="width:100%" cellpadding="7">
            <tr>
                <th>Question</th>
                <th>Outstanding</th>
                <th>Significant</th>
                <th>Satisfactory</th>
                <th>Minimal</th>
                <th>Bellow</th>
            </tr>
            <tr>
                
                <td width="50%">Attendance & punctuality</td>
                <td width="10%" ><input type="radio" value="5" name="q1"></td>
                <td width="10%" ><input type="radio" value="4" name="q1"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q1"></td>
                <td width="10%" ><input type="radio" value="2" name="q1"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q1"></td>
            </tr> 
            <tr>
                <td width="50%">Organized & well prepared</td>
                <td width="10%" ><input type="radio" value="5" name="q2"></td>
                <td width="10%" ><input type="radio" value="4" name="q2"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q2"></td>
                <td width="10%" ><input type="radio" value="2" name="q2"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q2"></td>
            </tr>
            <tr>
                <td width="50%">Works independently & Shows initiative</td>
                <td width="10%" ><input type="radio" value="5" name="q3"></td>
                <td width="10%" ><input type="radio" value="4" name="q3"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q3"></td>
                <td width="10%" ><input type="radio" value="2" name="q3"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q3"></td>
            </tr>
            <tr>
                <td width="50%">Meets deadlines</td>
                <td width="10%" ><input type="radio" value="5" name="q4"></td>
                <td width="10%" ><input type="radio" value="4" name="q4"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q4"></td>
                <td width="10%" ><input type="radio" value="2" name="q4"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q4"></td>
            </tr>
            <tr>
                <td width="50%">Good team worker</td>
                <td width="10%" ><input type="radio" value="5" name="q5"></td>
                <td width="10%" ><input type="radio" value="4" name="q5"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q5"></td>
                <td width="10%" ><input type="radio" value="2" name="q5"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q5"></td>
            </tr>
            <tr>
                <td width="50%">Attempts to acquire & apply new skills</td>
                <td width="10%" ><input type="radio" value="5" name="q6"></td>
                <td width="10%" ><input type="radio" value="4" name="q6"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q6"></td>
                <td width="10%" ><input type="radio" value="2" name="q6"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q6"></td>
            </tr>
            <tr>
                <td width="50%">Positive attitude & behaviour</td>
                <td width="10%" ><input type="radio" value="5" name="q7"></td>
                <td width="10%" ><input type="radio" value="4" name="q7"></td>                   
                <td width="10%" ><input type="radio" value="3" name="q7"></td>
                <td width="10%" ><input type="radio" value="2" name="q7"></td>                   
                <td width="10%" ><input type="radio" value="1" name="q7"></td>
            </tr>
            <tr>
                <td width="50%">Average:</td>
                <td width="10%" ><input type="name" value="" name="avg"></td>
                <td width="10%" ><input type="name" value="" name="avg"></td>                   
                <td width="10%" ><input type="name" value="" name="avg"></td>
                <td width="10%" ><input type="name" value="" name="avg"></td>                   
                <td width="10%" ><input type="name" value="" name="avg"></td>
            </tr>
            <tr>
                <td colspan="6">
                <input type="submit" value="Submit" name="submit-weekreport">
                </td>
            </tr>
        </table>
    </form>    
</div>

<script>
    function changeStudent() {
       var stlist = document.getElementById('studentslist');
       window.location.replace("./supfinalreport?sid="+stlist.value);
    }
</script>