<form method="post" onsubmit="return PassValid()" autocomplete="off">
    <?php 
        foreach ($this->Supinfo as $supinfo){
    ?>
    <div class="stlistpro">
        <div class="stlistprotop">
            <div class="stlistprotopname">
                <?php echo $supinfo['super_name'] ?>
            </div>
        </div>
        <div class="stlistprobottom" style="width: 100%; height: 450px;">
            <div class="stlistprobottomleft" style="width: 100%;">
                <h3 style="text-align: center; text-transform: uppercase;">Enter your details</h3>
                <input type="hidden" value="<?php echo $supinfo['supervisor_id'] ?>" name="supidprofile">
                <label style="width: 30%;">Email</label><input style="width: 100%;" type="text" id="sup-email" name="sup-email" value="<?php echo $supinfo['e_mail'] ?>" placeholder="Enter your email" />
                <br/><br/><label style="width: 30%;">Mobile</label><input style="width: 100%;" type="text" id="sup-mobile" name="sup-mobile" value="<?php echo $supinfo['phone'] ?>" placeholder="Enter your mobile number" />
                <input autocomplete="off" type="text" value=" " style="display: none;" placeholder="Enter your email" />
                <br/><br/><label style="width: 30%;">New Password</label><input style="width: 100%;" type="password" placeholder="Password" name="suppass" id="suppass" />
                <br/><br/><label style="width: 30%;">Confirm Password</label><input style="width: 100%;" type="password" placeholder="Confirm Password" name="confirm-suppass" id="confirm-suppass" />
            </div>
        </div>
    </div> 
    <?php
        }
    ?>
    <input style="width: 40%; margin-left: 30%;" type="submit" value="Save" name="save-supprofile">
</form>

<script>
    function PassValid() {
        var pass1 = document.getElementById("suppass").value;
        var pass2 = document.getElementById("confirm-suppass").value;
        
        var supemail = document.getElementById("sup-email").value;
        var supmobile = document.getElementById("sup-mobile").value;
        var ok = true;
        
        if (supemail === ""){
            alert("Please write your Email");
            ok = false;
        }else if (supmobile === ""){
            alert("Please write your Mobile");
            ok = false;
        }else if (pass1 !== pass2) {
            alert("Please match Password and Confirmation");
            ok = false;
        }
        
        return ok;
    }
</script>