<?php
    $stname="";
?>
<div class="moh-left-nav" >
    <a href="<?php echo $this->url('supworkplacement') ?>">Overview</a><br>
    <hr width="90%">
    <form method="post" style="width: 90%; margin: auto;">
        <!-- Students names-->
        <select id="studentslist" name="studentlist" onchange="changeStudent();" style="width:100%;">
           <?php 
                 foreach ($this->info as $student) :
                     if ($this->sid == $student['sid']){
                         $stname = $student['Student_Name'];
             ?>

             <option selected="selected" value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
             <?php
                     }else{
             ?>
             <option value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
             <?php
                     }
                 endforeach; 

             ?>
       </select>
       <br>
    </form>

    <a href="<?php echo $this->url('supworkplan', array(), array('query' => array('sid' => $this->sid)));?>"> Work plan </a> <br>
    <a href="<?php echo $this->url('supweeklyreport', array(), array('query' => array('sid' => $this->sid)));?>"> Evaluation Reports</a><br>
    <a href="<?php echo $this->url('supfinalreport', array(), array('query' => array('sid' => $this->sid)));?>"> Final Evaluation Report</a><br>
</div>

<div  class="moh-content">
    <center><h3><?php echo $stname; ?></h3></center>
    <center><h3>Weekly evaluation</h3></center>
</div>

<script>
    function changeStudent() {
       var stlist = document.getElementById('studentslist');
       window.location.replace("./supweeklyreport?sid="+stlist.value);
    }
</script>