<div class="moh-left-nav" >
    <a href="<?php echo $this->url('supervisor') ?>">Overview</a><br>
    <hr width="90%">
    <form method="post" style="width: 90%; margin: auto;">
        <!-- Students names-->
        <select id="studentslist" name="studentlist" onchange="changeStudent();" style="width:100%;">
           <?php 
               foreach ($this->info as $student) :
                   if ($i == 0){
                       $studentlistid = $student['sid'];
                   }
                   $i++;
           ?>
           <option  value="<?php echo $student['sid'] ?>"> <?php echo $student['Student_Name'] ?></option>
           <?php
               endforeach; 
           ?>
       </select>
       <br>
    </form>

    <a href="<?php echo $this->url('stwp', array(), array('query' => array('sid' => $studentlistid)));?>"> Work plan </a> <br>
    <a href="<?php echo $this->url('ster', array(), array('query' => array('sid' => $studentlistid)));?>"> Evaluation Reports</a><br>
    <a href="<?php echo $this->url('stfe', array(), array('query' => array('sid' => $studentlistid)));?>"> Final Evaluation Report</a><br>
</div>