
        <div class="moh-left-nav" >
            <a href="<?php echo $this->url('workplacement') ?>"> Information</a><br>
            <a href="<?php echo $this->url('workplan') ?>"> Work plan</a> <br>
            <a href="<?php echo $this->url('weeklyreport') ?>"> Weekly Report</a><br>  
            
        </div>
    
        <div  class="moh-content">
            <div>  
                <center> <h2> Student Work plan </h2> </center>
                    <hr>
                    <?php 

                        foreach ($this->Studentinfo as $student) :
                    //        echo 'Student Name     : '.$student['Student_Name'].'<br/><br/>';
                       //     echo 'Student ID       : '.$student['Student_id'].'<br/><br/>';
                            echo 'Company Name     : '.$student['org_name'].'.<br/><br/>';
                            echo 'Supervisor       : '.$student['super_name'].'<br/><br/>';
                            echo 'Supervisor phone : '.$student['phone'].'<br/><br/>';
                      //      echo 'Mentor Name      : '.$student['Teacher_FirstName']. ' '.$student['Teacher_LastName'].'<br/><br/>';
                        endforeach; 
                    ?>
            <div/> 
            
            <div>
                
                                <table border="1" style="width:100%" cellpadding="7">
                               <tr>
                                   <th>Week</th>
                                   <th>Department</th>
                                   <th>Work Assigned</th>
                                   <th> Supervisor Department  </th>

                               </tr>

                           <?php
                               foreach ($this->workplans as $workplan){

                               ?>
                               <tr>

                                    <td width="5%" ><?php echo $workplan['week'] ?></td>
                                    <td width="25%"><?php echo $workplan['department'] ?></td>
                                    <td width="50%" > <textarea class="mohtext"><?php echo $workplan['work_assigned'] ?></textarea></td>
                                    <td width="20%" ><?php echo $workplan['s_department'] ?></td>
                               </tr>   
                       <?php
                       } //foreach
                           ?>
                       </table>

                
            </div>
        </div> <!--moh-content-->
    
       