
<?php
if ($this->Step == "1"){
?>
    <h3>Add a new attendance entry</h3>
    <form method="post">
        <table style="width: 60%;">
            <tr>
                <td>
                    <select id="perpicker" name="periodadd" style="width:100%;">
                        <?php 
                            for ($i=1; $i<=5; $i++){
                                if($i == $this->pid){
                        ?>
                                    <option selected="selected" value="<?php echo $i ?>"><?php echo 'Period '.$i ?></option>
                        <?php
                                }else{
                        ?>
                                    <option value="<?php echo $i ?>"><?php echo 'Period '.$i ?></option>
                        <?php                        
                                }
                            }
                        ?>
                    </select>                
                </td>
                <td>
                    <select id="secpicker" name="secadd" style="width:100%;">
                        <?php 
                            foreach ($this->sections as $section) :
                                if($section['Section_id']==$this->secid){
                        ?>
                                <option selected="selected" value="<?php echo $section['Section_id'] ?>">Section <?php echo $section['Section_id'] ?></option>
                        <?php
                                }else{
                        ?>
                                <option value="<?php echo $section['Section_id'] ?>">Section <?php echo $section['Section_id'] ?></option>
                        <?php
                                }
                            endforeach; 
                        ?>
                    </select>
                </td>
                <td>
                    <select id="teapicker" name="teaadd" style="width:100%;">
                        <?php 
                            foreach ($this->teachers as $teacher) :
                                if ($teacher['Teacher_id']==$this->tid){
                        ?>
                                    <option selected="selected" value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                        <?php
                                }else{
                        ?>
                                    <option value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                        <?php
                                }
                            endforeach; 
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="sdatepicker" name="addday" value="<?php echo $this->day ?>" placeholder="Pick a date" />
                </td>
                <td>
                    <input type="submit" value="Next" name="next-but">
                </td>
            </tr>
        </table>
    </form>

<?php }else if ($this->Step == "2"){ ?>
    <h3>Add a new attendance entry</h3>
    <h3><?php echo 'For section '.$this->section.' period '.$this->period.' on '.$this->wradday ?></h3>
    <form action ="" method="post" style="width: 75%; margin: auto;">
        <?php
        $count=0;
        ?>
        <input type="hidden" value="<?php echo $this->teacher ?>" name="addt" />
        <input type="hidden" value="<?php echo $this->period ?>" name="addp" />
        <input type="hidden" value="<?php echo $this->adday ?>" name="addd" />
        <table border="1" style="width:100%">
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
                <th> Present </th>
                <th> Late </th>
                <th> Absent </th>
            </tr>
        <?php
        foreach ($this->students as $student){
        $count= $count + 1;
        ?>
        <input type="hidden" value="<?php echo $student['sid'] ?>" name="<?php echo 'idstudent'.$count ?>">
        <tr>
            <th><?php echo $count ?></th>
            <th><?php echo $student['Student_id'] ?></th>
            <th style="text-align: left;"><?php echo $student['Student_Name']; ?>  </th>
            <th><input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="0" checked="checked"> </th>
            <th><input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="1" ></th>
            <th><input type ="radio" name ="<?php echo 'attendance'.$count ?>" value="3" ></th>
        </tr>   
        <?php
        }
        ?>
        </table>
        <input type="hidden" value="<?php echo $count?>" name="stcount">

        <input type="submit" value="submit" name="submit-but">
    </form>
<?php }else{ ?>
    <h3>New entry successful</h3>
<?php } ?>

