 <form method="post" style="width: 70%; margin: auto; text-align: center;">
     <span style="text-align: center;">Are you sure you wish to delete student <b><?php echo $this->stname ?></b> from <b>section <?php echo $this->secid ?></b>?</span>
    <br/><input type="submit" value="Yes" name="yes-but" style="cursor: pointer; width: 20%; margin-left: 5px; margin-right: 5px; margin-top: 25px;">
    <input type="submit" value="No" name="no-but" style="cursor: pointer; width: 20%; margin-left: 5px; margin-right: 5px; margin-top: 25px;">
 </form> 