<script>
function ActivateCommment(i){
    var box = document.getElementById("rattendance"+i);
    var comment = document.getElementById("rcomment"+i);
    if (box.checked){
        box.value = 1;
        comment.value = "";
        comment.disabled = true;
    }else{
        box.value = 0;
        comment.value = "";
        comment.disabled = false;
    }
}
</script>
<?php 
if ($this->message != ""){
    echo $this->message;
}
?>
<!-- begin of my code -->
 <div id ="att_header">
    <h3><?php echo $this->filter ?></h3>
    </div> <!-- att_header -->   
    <form method="post">
        <table style="width: 60%;">
            <tr>
                <td>
                    <select id="statuspicker" name="status-filter" style="width:100%;">
                        <?php 
                            if($this->status == 1){
                        ?>
                                <option value=0>All status</option>
                                <option value="3">Absent</option>
                                <option selected="selected" value="1">Late</option>
                        <?php
                            }else if($this->status == 3){
                        ?>
                                <option value=0>All status</option>
                                <option selected="selected" value="3">Absent</option>
                                <option value="1">Late</option>
                        <?php                        
                            }else{
                        ?>
                                <option selected="selected" value=0>All status</option>
                                <option value="3">Absent</option>
                                <option value="1">Late</option>
                                    
                        <?php
                            }
                        ?>
                    </select>  
                </td>
                <td>
                    <select id="secpicker" name="sec-filter" style="width:100%;">
                        <option  value=0>All sections</option>
                        <?php 
                            foreach ($this->sections as $section) :
                                if($section['Section_id']==$this->secid){
                        ?>
                                <option selected="selected" value="<?php echo $section['Section_id'] ?>">Section <?php echo $section['Section_id'] ?></option>
                        <?php
                                }else{
                        ?>
                                <option value="<?php echo $section['Section_id'] ?>">Section <?php echo $section['Section_id'] ?></option>
                        <?php
                                }
                            endforeach; 
                        ?>
                    </select>
                </td>
                <td>
                    <select id="teapicker" name="tea-filter" style="width:100%;">
                        <option  value=0>All teachers</option>
                        <?php 
                            foreach ($this->teachers as $teacher) :
                                if ($teacher['Teacher_id']==$this->tid){
                        ?>
                                    <option selected="selected" value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                        <?php
                                }else{
                        ?>
                                    <option value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                        <?php
                                }
                            endforeach; 
                        ?>
                    </select>
                </td>
                <td>
                    <select id="perpicker" name="p-filter" style="width:100%;">
                        <option  value=0>All periods</option>
                        <?php 
                            for ($i=1; $i<=5; $i++){
                                if($i == $this->pid){
                        ?>
                                    <option selected="selected" value="<?php echo $i ?>"><?php echo 'Period '.$i ?></option>
                        <?php
                                }else{
                        ?>
                                    <option value="<?php echo $i ?>"><?php echo 'Period '.$i ?></option>
                        <?php                        
                                }
                            }
                        ?>
                    </select>                
                </td>
                <td>
                    
                </td>
            </tr>
            <tr>
                <td>
                    <br/><br/>
                    <input type="text" id="stidpicker" name="stid-filter" value="<?php echo $this->stid ?>" placeholder="Student ID" />
                </td>
                <td>
                    <br/>From: <input type="text" id="sdatepicker" name="sdate-filter" value="<?php echo $this->sday ?>" placeholder="Pick a start date" />
                </td>
                <td>
                    <br/>To: <input type="text" id="edatepicker" name="edate-filter" value="<?php echo $this->eday ?>" placeholder="Pick an end date" />
                </td>
                <td>
                    <br/><br/>
                    <input type="submit" value="Filter" name="submit-date">
                </td>
            </tr>
        </table>
        <br/><br/>
       <table border="1" style="width:100%">
           <tr>
               <th> ID       </th>
               <th> Section  </th>
               <th> Name     </th>
               <th> Period   </th>
               <th> Teacher   </th>
               <th> Date </th>
               <th> Time   </th>
               <th> Status   </th>
               <th> Counted  </th>
               <th> Comment </th>
    <?php
    $count=0;
    foreach ($this->attendance as $student){
     $count++;
     ?>   
      <input type="hidden" value="<?php echo $student['Att_id'] ?>" name="<?php echo 'rid'.$count ?>">
      <tr>
        <td style="text-align: center;"><?php echo $student['Student_id'] ?></td>
        <td style="text-align: center;"><?php echo $student['Student_Section']?></td>
        <td><?php echo $student['Student_Name']?> </td>
        <td style="text-align: center;"><?php echo $student['Abs_period']?> </td>
        <td style="text-align: center;"><?php echo $student['Teacher_FirstName']?> </td>
        <td style="text-align: center;"><?php echo $student['Abs_Day']?> </td>
        <td style="text-align: center;"><?php echo $student['att_time']?></td>
 
        <td>
            <select id="statusupdate" name="<?php echo 'status-update'.$count ?>" style="width:100%;">
                <?php 
                    if($student['Abs_value'] == 1){
                ?>
                        <option value=0>Present</option>
                        <option value="3">Absent</option>
                        <option selected="selected" value="1">Late</option>
                <?php
                    }else if($student['Abs_value'] == 3){
                ?>
                        <option value=0>Present</option>
                        <option selected="selected" value="3">Absent</option>
                        <option value="1">Late</option>
                <?php                        
                    }
                ?>
            </select>  
        </td>
        <?php if ($student['counted'] == 1){ ?>
            <td><input type ="checkbox" name ="<?php echo 'rattendance'.$count ?>" id ="<?php echo 'rattendance'.$count ?>" value="1" checked onchange="ActivateCommment(<?php echo $count ?>)"></td>
            <td><input type ="text" name ="<?php echo 'rcomment'.$count ?>" id ="<?php echo 'rcomment'.$count ?>" value="<?php echo $student['comment']; ?>" disabled></td>
        <?php }else{ ?>
            <td><input type ="checkbox" name ="<?php echo 'rattendance'.$count ?>" id ="<?php echo 'rattendance'.$count ?>" value="0" onchange="ActivateCommment(<?php echo $count ?>)"></td>
            <td><input type ="text" name ="<?php echo 'rcomment'.$count ?>" id ="<?php echo 'rcomment'.$count ?>" value="<?php echo $student['comment']; ?>"></td>
        <?php } ?>
    </tr>               
    <?php } ?>
      </table>
            <input type="hidden" value="<?php echo $count?>" name="rcount">
            <input type="submit" value="submit" name="submit-update">
        </form>
    </div>
 <!-- end of my code -->