<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
</style>
<?php
  //echo 'Student id: '.$this->id;
foreach ($this->stprofile as $student3) {
    echo '<h3 > Student Name : '.$student3['Student_Name'].'</h3>';
    echo '<br>';
}
$i=0;   
 foreach ($this->std as $student) {
    $i++;
    if ($this->id == $student['sid'])
    {
    // echo $student['sid'];
 //    echo '<br>';
  
    foreach ($this->stdays as $student2 ) {
    
    if ($this->id == $student2['sid'])
            {
                echo '<table style="width :20%" > ';
                echo '         <tr> ';
                echo '          <th bgcolor="#ffe6b3"> Total Days </th>';
                echo '          <th bgcolor="#ffe6b3">'.$student2['Days'].'</th>';
                echo '         </tr>';
                echo '<table>';
             }
        }
     echo '<hr>';
     
     echo '<table style="width :100%" > ';
     echo '         <tr> ';
     echo '          <th colspan="10" bgcolor="#00FF00"> Absent      </th>';
     echo '         </tr>';
     
     echo '         <tr> ';
     echo '          <th colspan="2"> Work Skills </th>';
     echo '          <th colspan="2"> English     </th>';
     echo '          <th colspan="2"> Computer    </th>';
     echo '          <th colspan="2"> Math        </th>';
     echo '          <th colspan="2"> Arabic      </th>';
     echo '          </tr>';
     
     echo '         <tr>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          </tr>';
     
     echo '           <tr>';
     echo '             <td>'.$student['wk_counted'].'</td>';
     echo '             <td>'.$student['wk_removed'].'</td>';
     
     echo '             <td>'.$student['en_counted'].'</td>';
     echo '             <td>'.$student['en_removed'].'</td>';
    
     echo '             <td>'.$student['co_counted'].'</td>';
     echo '             <td>'.$student['co_removed'].'</td>';
     
     echo '             <td>'.$student['ma_counted'].'</td>';
     echo '             <td>'.$student['ma_removed'].'</td>';
     
     echo '             <td>'.$student['ar_counted'].'</td>';
     echo '             <td>'.$student['ar_removed'].'</td>';
            
     echo '            </tr>';
     // late 
     echo '         <tr> ';
     echo '          <th colspan="10" bgcolor="#00FF00"> Late     </th>';
     echo '         </tr>';
     
     echo '         <tr> ';
     echo '          <th colspan="2"> Work Skills </th>';
     echo '          <th colspan="2"> English     </th>';
     echo '          <th colspan="2"> Computer    </th>';
     echo '          <th colspan="2"> Math        </th>';
     echo '          <th colspan="2"> Arabic      </th>';
     echo '          </tr>';
     
     echo '         <tr>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>';
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          <td>Counted</td>';
     echo '          <td>Un Counted</td>'; 
     echo '          </tr>';
     
     echo '           <tr>';
     echo '             <td>'.$student['wk_countedl'].'</td>';
     echo '             <td>'.$student['wk_removedl'].'</td>';
     
     echo '             <td>'.$student['en_countedl'].'</td>';
     echo '             <td>'.$student['en_removedl'].'</td>';
    
     echo '             <td>'.$student['co_countedl'].'</td>';
     echo '             <td>'.$student['co_removedl'].'</td>';
     
     echo '             <td>'.$student['ma_countedl'].'</td>';
     echo '             <td>'.$student['ma_removedl'].'</td>';
     
     echo '             <td>'.$student['ar_countedl'].'</td>';
     echo '             <td>'.$student['ar_removedl'].'</td>';
            
     echo '            </tr>';
     //total
     
     echo '         <tr bgcolor="#FF0000"> ';
     echo '          <th colspan="2"> Work Skills Counted </th>';
     echo '          <th colspan="2"> English Counted  </th>';
     echo '          <th colspan="2"> Computer Counted   </th>';
     echo '          <th colspan="2"> Math Counted    </th>';
     echo '          <th colspan="2"> Arabic Counted     </th>';
     echo '          </tr>';
     
     echo '         <tr> ';
                        $sum =$student['wk_counted'] + (int) ($student['wk_countedl'] / 3 ) ;
     echo '          <th colspan="2"> ' .$sum .  '</th>';
                        $sum =$student['en_counted'] + (int)($student['en_countedl'] / 3 );
     echo '          <th colspan="2">' .$sum .  ' </th>';
                        $sum =$student['co_counted'] + (int)($student['co_countedl'] / 3 );
     echo '          <th colspan="2"> ' .$sum .  '   </th>';
                        $sum =$student['ma_counted'] + (int)($student['ma_countedl'] / 3 );
     echo '          <th colspan="2"> ' .$sum .  '    </th>';
                        $sum =$student['ar_counted'] + (int)($student['ar_countedl'] / 3 );
     echo '          <th colspan="2"> ' .$sum .  '    </th>';
     echo '          </tr>';
     
     echo '          </table>';

   
    }
 }
 if ($i === 0){
        echo '<table style="width :20%" > ';
        echo '         <tr> ';
        echo '          <th bgcolor="#ffe6b3"> Total Days </th>';
        echo '          <th bgcolor="#ffe6b3">0</th>';
        echo '         </tr>';
        echo '<table>';

        echo '<hr>';

        echo '<table style="width :100%" > ';
        echo '         <tr> ';
        echo '          <th colspan="10" bgcolor="#00FF00"> Absent      </th>';
        echo '         </tr>';

        echo '         <tr> ';
        echo '          <th colspan="2"> Work Skills </th>';
        echo '          <th colspan="2"> English     </th>';
        echo '          <th colspan="2"> Computer    </th>';
        echo '          <th colspan="2"> Math        </th>';
        echo '          <th colspan="2"> Arabic      </th>';
        echo '          </tr>';

        echo '         <tr>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          </tr>';

        echo '           <tr>';
        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '            </tr>';
        // late 
        echo '         <tr> ';
        echo '          <th colspan="10" bgcolor="#00FF00"> Late     </th>';
        echo '         </tr>';

        echo '         <tr> ';
        echo '          <th colspan="2"> Work Skills </th>';
        echo '          <th colspan="2"> English     </th>';
        echo '          <th colspan="2"> Computer    </th>';
        echo '          <th colspan="2"> Math        </th>';
        echo '          <th colspan="2"> Arabic      </th>';
        echo '          </tr>';

        echo '         <tr>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>';
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          <td>Counted</td>';
        echo '          <td>Un Counted</td>'; 
        echo '          </tr>';

        echo '           <tr>';
        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '             <td>0</td>';
        echo '             <td>0</td>';

        echo '            </tr>';
        //total

        echo '         <tr bgcolor="#FF0000"> ';
        echo '          <th colspan="2"> Work Skills Counted </th>';
        echo '          <th colspan="2"> English Counted  </th>';
        echo '          <th colspan="2"> Computer Counted   </th>';
        echo '          <th colspan="2"> Math Counted    </th>';
        echo '          <th colspan="2"> Arabic Counted     </th>';
        echo '          </tr>';

        echo '         <tr> ';
        echo '          <th colspan="2">0</th>';
        echo '          <th colspan="2">0</th>';
        echo '          <th colspan="2">0</th>';
        echo '          <th colspan="2">0</th>';
        echo '          <th colspan="2">0</th>';
        echo '          </tr>';

        echo '          </table>';

 }
    
   
?>