<div class="sttabs">
    <ul class="sttab-links">
        <?php 
            $i=0;
            foreach ($this->sections as $section) :
                if($i==0){
                    $i++;
        ?>
                    <li class="active"><a href="#<?php echo $i ?>"><?php echo 'Section '.$section['Section_id'] ?></a></li>
        <?php
                }else{
                    $i++;
        ?>          
                    <li><a href="#<?php echo $i ?>"><?php echo 'Section '.$section['Section_id'] ?></a></li>
        <?php
                }
            endforeach; 
        ?>
    </ul>

    <div class="sttab-content">
        <?php 
            $j=0;
            foreach ($this->sections2 as $section2) :
                if($j==0){
                    $j++;
        ?>
                    <div id="<?php echo $j ?>" class="sttab active">
                        <table border="1" style="width:100%">
                            <tr>
                                <th> Number  </th>
                                <th> ID      </th>
                                <th> Name    </th>
                                <th> Section </th>
                                <th> days    </th>
                            </tr>
                        <?php 
                        $count = 0;
                        foreach ($this->students as $student){
                            if ($section2['Section_id'] == $student['Student_Section']){
                                $count++;
                        ?>
                            
                            <tr>
                                <th><?php echo $count ?></th>
                                <th><a href="streport?id=<?php echo $student['sid'] ?>"><?php echo $student['Student_id'] ?></a></th>
                                <th><?php echo $student['Student_Name'] ?></th>
                                <th><?php echo $student['Student_Section'] ?></th>
                              
                                <?php
                                $Days ='0';   
                                foreach ($this->studentsAbs as $studentAbs){
                                       
                                    if ($studentAbs['sid'] == $student['sid']){
                                         $Days =$studentAbs['Days'];
                                ?>
                               
                                 
                                <?php } } ?>
                                 <th><?php echo $Days ?></th>
                            </tr>
                            
                        <?php 
                            }}
                        ?>
                        </table>
                    </div>
     
        <?php
                }else{
                    $j++;
        ?>
                    <div id="<?php echo $j ?>" class="sttab">
                        <table border="1" style="width:100%">
                            <tr>
                                <th> Number</th>
                                <th>ID</th>
                                <th>Name</th>
                                <th> Section </th>
                                <th>days </th>
                            </tr>
                        <?php 
                        $count = 0;
                        foreach ($this->students as $student){
                            if ($section2['Section_id'] == $student['Student_Section']){
                                $count++;
                        ?>
                            
                            <tr>
                                <th><?php echo $count ?></th>
                                <th><a href="streport?id=<?php echo $student['sid'] ?>"><?php echo $student['Student_id'] ?></a></th>
                                <th><?php echo $student['Student_Name'] ?></th>
                                <th><?php echo $student['Student_Section'] ?></th>
                               
                                   <?php
                                   $Days ='0';
                                foreach ($this->studentsAbs as $studentAbs){
                                       
                                    if ($studentAbs['sid'] == $student['sid']){
                                             $Days =$studentAbs['Days'];
                                ?>
                                
                                 
                                <?php } }?>
                                <th><?php echo $Days ?></th>
                            </tr>

                        <?php 
                            }}
                        ?>
                        </table>
                    </div>
        <?php
                }
            endforeach; 
        ?>
    </div>
</div>