<div class="moh-left-nav" >
    <a href="<?php echo $this->url('adminwkp'); ?>">Students</a><br>
    <a href="<?php echo $this->url('adminwkplaces'); ?>">Work Places</a><br>
    <a href="<?php echo $this->url('adminsupervisors'); ?>">Supervisors</a><br>
</div>

<div  class="moh-content">
    <div class="sttabs">
        <ul class="sttab-links">
            <?php 
                $i=0;
                foreach ($this->sections as $section) :
                    if($i==0){
                        $i++;
            ?>
                        <li class="active"><a href="<?php echo $this->url('adminwkp', array(), array('query' => array( 'secid' => $i ) ));?>"><?php echo 'Section '.$section['Section_Name'] ?></a></li>
            <?php
                    }else{
                        $i++;
            ?>          
                        <li><a href="<?php echo $this->url('adminwkp', array(), array('query' => array( 'secid' => $i ) ));?>"><?php echo 'Section '.$section['Section_Name'] ?></a></li>
            <?php
                    }
                endforeach; 
            ?>
        </ul>

        <div class="sttab-content">
            <div class="sttab active">
                <?php 
                $stcount = 0;
                foreach ($this->students as $student){
                    if ($this->secid == $student['Student_Section']){
                        $stcount++;
                        if($stcount == 1){
                ?>
                <h2 style="width: 75%; margin:0px auto 0px auto;">Section <?php echo $student['Section_Name'] ?></h2>
                <?php
                }
                ?>
                <div class="stlistpro">
                    <div class="stlistprotop">
                        <div class="stlistprotopname">
                            <?php echo $student['Student_Name'] ?>
                        </div>
                        <div class="stlistprotophid">
                            <!--<a href="streport?id=<?php echo $student['sid'] ?>"> -->
                                <?php 
                                    if ($student['Student_id'] == ""){
                                        echo "No ID";
                                    }else{
                                        echo $student['Student_id'];
                                    }
                                ?>
                            <!--</a>-->
                        </div>
                    </div>
                    <div class="stlistprobottom">
                        <div class="stlistprobottomleft">
                            
                        </div>
                        <div class="stlistprobottomright">
                            
                        </div>
                    </div>
                </div>  
                <?php 
                    }}
                ?>
            </div>
        </div>
    </div>
</div>