<div class="moh-left-nav" >
    <a href="<?php echo $this->url('adminwkp'); ?>">Students</a><br>
    <a href="<?php echo $this->url('adminwkplaces'); ?>">Work Places</a><br>
    <a href="<?php echo $this->url('adminsupervisors'); ?>">Supervisors</a><br>
    <a href="<?php echo $this->url('adminmentors'); ?>">Mentors</a><br>
</div>

<div  class="moh-content">
    <form style="width:50%;" method="post">
        <h3 style="margin-bottom: 0px;">Add a new work place</h3>
        <hr>
        <input style="width: 80%; float: left;" type="text" id="stidpicker" name="new-cmp-name" value="<?php echo $this->stid ?>" placeholder="Add a new work place" />
        <input style="width: 18%; float: right;" type="submit" value="Add" name="add-cmp">
    </form>
    <h3 style="margin-top: 100px; margin-bottom: 0px;">Companies</h3>
    <hr>
    <?php
        $cmp = "";
        foreach ($this->companies as $company) :
            if($cmp != $company['Company_Name']){
                if($cmp != ""){
                ?>
                    </table>
                    </article>
                <?php
                }
                $cmp = $company['Company_Name'];
            ?>
                <article class="companylist">
                    <p style="margin: 0px; font-weight: bold;"><?php echo $company['Company_Name'] ?></p><hr>
                    <table style="width: 95%; margin: auto;"  border="1" cellpadding="7">
                        <tr>
                            <th style="text-align: left;">Name</th>
                            <th style="text-align: left;">Phone</th>
                            <th style="text-align: left;">Email</th>
                            <th style="text-align: left;">Branch</th>
                        </tr>
            <?php
            }
            ?>
                        <tr>
                            <td width="25%" ><?php echo $company['super_name']?></td>
                            <td width="30%"><?php echo $company['phone']?></td>
                            <td width="30%" ><?php echo $company['e_mail']?></td>
                            <td width="15%" ><?php echo $company['branch']?></td>
                       </tr>  
            <?php              
        endforeach;
    ?>
        </table>
    </article>
</div>