<div class="moh-left-nav" >
    <a href="<?php echo $this->url('adminwkp'); ?>">Students</a><br>
    <a href="<?php echo $this->url('adminwkplaces'); ?>">Work Places</a><br>
    <a href="<?php echo $this->url('adminsupervisors'); ?>">Supervisors</a><br>
    <a href="<?php echo $this->url('adminmentors'); ?>">Mentors</a><br>
</div>

<div  class="moh-content">
    <div class="sttabs">
        <ul class="sttab-links">
            <?php 
                $i=0;
                foreach ($this->sections as $section) :
                    if($i==0){
                        $i++;
            ?>
                        <li class="active"><a href="<?php echo $this->url('adminwkp', array(), array('query' => array( 'secid' => $i ) ));?>"><?php echo 'Section '.$section['Section_Name'] ?></a></li>
            <?php
                    }else{
                        $i++;
            ?>          
                        <li><a href="<?php echo $this->url('adminwkp', array(), array('query' => array( 'secid' => $i ) ));?>"><?php echo 'Section '.$section['Section_Name'] ?></a></li>
            <?php
                    }
                endforeach; 
            ?>
        </ul>

        <div class="sttab-content">
            <div class="sttab active">
                <form method="post">
                <?php 
                $stcount = 0;
                foreach ($this->students as $student){
                    if ($this->secid == $student['Student_Section']){
                        $stcount++;
                        if($stcount == 1){
                ?>
                <h2 style="width: 75%; margin:0px auto 0px auto;">Section <?php echo $student['Section_Name'] ?></h2>
                <?php
                }
                ?>
                <div class="stlistpro">
                    <div class="stlistprotop">
                        <div class="stlistprotopname">
                            <?php echo $student['Student_Name'] ?>
                        </div>
                        <div class="stlistprotophid">
                                <?php 
                                    if ($student['Student_id'] == ""){
                                        echo "No ID";
                                    }else{
                                        echo $student['Student_id'];
                                    }
                                ?>
                            <!--</a>-->
                        </div>
                    </div>
                    <div class="stlistprobottom" style="width: 100%; height: 60px;">
                        <div class="stlistprobottomleft" style="width: 60%; float: left;">
                            <input type="hidden" value="<?php echo $student['sid'] ?>" name="<?php echo 'stwkid'.$stcount ?>">
                            <label style="width: 30%;">Mentor</label>
                            <select name="<?php echo 'mentorlink'.$stcount ?>" style="width:70%; float: right;">
                                        <option value="0">No Mentor</option>
                                <?php 
                                    foreach ($this->teachers as $teacher) :
                                        if ($teacher['Teacher_id'] == $student['mentor_id']){
                                ?>
                                        <option selected="selected" value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                                <?php
                                        }else{
                                ?>
                                        <option value="<?php echo $teacher['Teacher_id'] ?>"><?php echo $teacher['Teacher_FirstName'].' '.$teacher['Teacher_LastName'] ?></option>
                                <?php            
                                        }
                                    endforeach; 
                                ?>
                            </select>
                            <label style="width: 30%;">Supervisor</label>
                            <select name="<?php echo 'supervisorlink'.$stcount ?>" style="width:70%; float: right;">
                                        <option value="0">No Supervisor</option>
                                <?php 
                                    foreach ($this->supervisors as $supervisor) :
                                        if ($supervisor['supervisor_id'] == $student['super_id']){
                                ?>
                                        <option selected="selected" value="<?php echo $supervisor['supervisor_id'] ?>"><?php echo $supervisor['Company_Name'].' - '.$supervisor['branch'].' - '.$supervisor['super_name'] ?></option>
                                <?php
                                        }else{
                                ?>
                                        <option value="<?php echo $supervisor['supervisor_id'] ?>"><?php echo $supervisor['Company_Name'].' - '.$supervisor['branch'].' - '.$supervisor['super_name'] ?></option>
                                <?php
                                        }
                                    endforeach; 
                                ?>
                            </select>
                        </div>
                    </div>
                </div>  
                <?php 
                    }}
                    if($stcount != 0){
                ?>
                <input type="hidden" value="<?php echo $stcount?>" name="stcount">
                <input style="width: 50%; margin-left: 25%;" type="submit" value="submit" name="submit-wk-link">
                <?php
                    }
                ?>
                </form>
            </div>
        </div>
    </div>
</div>