<div class="moh-left-nav" >
    <a href="<?php echo $this->url('adminwkp'); ?>">Students</a><br>
    <a href="<?php echo $this->url('adminwkplaces'); ?>">Work Places</a><br>
    <a href="#">Supervisors</a><br>
</div>

<div  class="moh-content">
    <form style="width:50%;" method="post">
        <h3 style="margin-bottom: 0px;">Add a new work place</h3>
        <hr>
        <input style="width: 80%; float: left;" type="text" id="stidpicker" name="new-cmp-name" value="<?php echo $this->stid ?>" placeholder="Add a new work place" />
        <input style="width: 18%; float: right;" type="submit" value="Add" name="add-cmp">
    </form>
    <h3 style="margin-top: 100px; margin-bottom: 0px;">Companies</h3>
    <hr>
    <?php
        $cmp = "";
        foreach ($this->companies as $company) :
            if($cmp != $company['Company_Name']){
                if($cmp != ""){
                ?>
                    </article>
                <?php
                }
                $cmp = $company['Company_Name'];
            ?>
                <article class="companylist">
                    <p style="margin: 0px; font-weight: bold;"><?php echo $company['Company_Name'] ?></p><hr>
            <?php
            }
            ?>
                    <content class="companylistcontent">
                        <p><?php echo $company['super_name']?></p> 
                        <p><?php echo $company['phone']?></p> 
                        <p><?php echo $company['e_mail']?></p> 
                        <p><?php echo $company['branch']?></p>
                    </content>
            <?php              
        endforeach;
    ?>
                </article>
</div>